version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:erbium

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run: ./build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: .

  docs-deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Add github.com to known hosts
          command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git config user.email "vankeisb-ci@rvkb.com"
      - run: git config user.name "vankeisb-ci"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^gh-pages$/
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: main
